import { BrainCircuit, Database, Layers3, BarChart3, Smartphone } from "lucide-react";
export const projects = [
 {id:"supportdesk",number:"01",title:"AI Support Desk Analytics",category:"AI ANALYTICS PLATFORM",date:"2025",theme:"support",description:"Natural-language analytics over 500 support tickets — no SQL required.",stack:["Python","FastAPI","Streamlit","SQLite","Pydantic","Ollama","Groq","Docker"],metric:"500",metricLabel:"support tickets analysed",Icon:BarChart3,question:"Can an LLM turn plain-English questions into reliable analytics without writing SQL?",introduction:"A full-stack AI application that helps support teams analyse customer-service tickets without writing SQL. The system ingests a CSV dataset, validates the schema, stores the records in SQLite, answers natural-language questions, and highlights potentially problematic tickets. The application uses an LLM only to understand the user's question and produce a restricted analytics plan. Pydantic validates that plan, while deterministic Python code performs the actual calculations — improving reliability and preventing the model from directly generating unsafe or unpredictable SQL.",sections:[
  ["The challenge","Support teams have valuable data locked in ticket records, but querying it requires SQL skills most agents don't have. The goal was to make that data conversational — without sacrificing accuracy or safety."],
  ["LLM-to-JSON planning workflow","The system converts natural-language questions into validated analytics operations. The LLM produces a structured JSON plan; Pydantic validates it; deterministic Python executes counts, averages, rankings, filters, and time-based analysis."],
  ["Anomaly detection","Implemented explainable anomaly detection using IQR-based resolution-time analysis and a 24-hour unresolved High/Critical ticket rule. The system identified 21 long-resolution tickets and 80 aging priority tickets, plus 28 records with inconsistent timing information."],
  ["What it includes","CSV schema validation and SQLite ingestion · REST API with FastAPI and Swagger docs at /docs · Streamlit dashboard with Overview, Ask the Data, Anomalies, Tickets, and Setup pages · Ticket search and filtering · Summary statistics and agent performance analysis · Ollama support with optional Groq integration · 18 automated tests · Docker configuration."],
  ["Outcome","The system successfully transformed a 500-row support-ticket dataset into a queryable analytics application. Its validation and anomaly checks identified 21 unusually long-resolution tickets, 80 unresolved aging High/Critical tickets, and 28 records with inconsistent timing information."]],note:"The LLM is used only for structured natural-language understanding. All analytics are performed by deterministic Python — not generated SQL. The system was not deployed to production.",github:"https://github.com/Johnapatel/support-desk-assessment"},
 {id:"echomind",number:"02",title:"EchoMind",category:"CONVERSATIONAL AI",date:"FEB — MAY 2026",theme:"echo",description:"Turning personal context into a conversation that feels familiar.",stack:["Next.js","TypeScript","React","Gemini API"],metric:"10",metricLabel:"persona test samples",Icon:BrainCircuit,question:"How can a conversation reflect a person's context?",introduction:"EchoMind is a digital persona reconstruction platform. The project brings personal context into an AI conversation, with a focus on keeping the persona consistent across responses.",sections:[
  ["The challenge","A conversational interface needs more than a model connection. It needs a way to carry relevant context into each exchange so that responses stay aligned with the intended persona."],
  ["My contribution","I architected the full-stack conversational platform using Next.js, TypeScript and React. I integrated the Gemini API and implemented prompt engineering and context management for persona-based responses."],
  ["How it comes together","The application connects the conversation interface to the Gemini API. Persona context informs the prompt, and the generated response returns to the conversation. Prompt structure and context management are the central pieces of that flow."],
  ["What I tested","I validated the platform across 10 real-world persona test samples. Direct API integration delivered near real-time responses, while prompt engineering and context management supported consistent persona-based conversation."]],note:"Validation scope: 10 real-world persona test samples.",github:"https://github.com/Johnapatel"},
 {id:"smartmart",number:"03",title:"SmartMart",category:"DATA ENGINEERING",date:"JUL — DEC 2024",theme:"mart",description:"From raw retail records to a warehouse built for questions.",stack:["Python","Pandas","PostgreSQL","SQL"],metric:"20k+",metricLabel:"retail records processed",Icon:Database,question:"How do you turn transaction data into useful answers?",introduction:"SmartMart is a retail data warehouse and ETL project covering one year of sales records. It turns transaction data into a structured foundation for business analysis.",sections:[
  ["The challenge","Sales, customers and products need to be analysed together. That requires consistent data preparation and a database structure that makes those relationships easy to query."],
  ["My contribution","I built an end-to-end Python pipeline to clean, transform and load more than 20,000 retail records into PostgreSQL. Pandas handled the data preparation."],
  ["A structure for analysis","I designed a star-schema warehouse around sales, customer and product dimensions. SQL supported analysis, while Matplotlib visualisations helped communicate sales and customer trends."],
  ["The outcome","The result was a working ETL pipeline, a star-schema warehouse and visualisations of sales and customer trends, built around more than 20,000 records spanning one year."]],note:"Project scope: one year of retail transaction data, from preparation to analysis.",github:"https://github.com/Johnapatel"},
 {id:"nutritionist",number:"04",title:"ML Nutritionist",category:"APPLIED MACHINE LEARNING",date:"JAN — MAY 2024",theme:"nutrition",description:"Exploring personalised nutrition through machine learning.",stack:["Python","Pandas","NumPy","Scikit-learn"],metric:"1,200+",metricLabel:"records in the data pipeline",Icon:Layers3,question:"Can structured data support more personal diet planning?",introduction:"ML Nutritionist explores nutrient prediction and diet-type recommendations through regression and classification models.",sections:[
  ["The challenge","The project combines two different modelling tasks: predicting continuous nutrient and calorie targets, and recommending a diet category."],
  ["My contribution","I built a Python pipeline for more than 1,200 healthcare records, using Pandas and NumPy for data cleaning and feature engineering. I also automated preprocessing and generated analytical insights."],
  ["The modelling approach","Regression models predicted nutrient and calorie targets. Random Forest, SVM and KNN classifiers were explored for diet-type recommendations, using Scikit-learn."],
  ["Reported results","The project evaluation reported an R² of 0.94 for nutrient and calorie prediction, and 88% classification accuracy for diet-type recommendations. These are project-level results; evaluation splits and external validation are not documented in this portfolio."]],note:"An academic machine learning project, not a clinically validated recommendation system.",github:"https://github.com/Johnapatel"},
 {id:"wellnest",number:"05",title:"WellNest",category:"FULL-STACK WEB APP",date:"ELDERCARE & HOSPITAL CONNECTION",theme:"wellnest",description:"Connecting families, doctors and eldercare through one platform.",stack:["React","Node.js","Express.js","PostgreSQL","Firebase","Gemini API"],metric:"Full-stack",metricLabel:"eldercare platform",Icon:BrainCircuit,question:"How can families stay connected to eldercare?",introduction:"WellNest is an AI-powered eldercare and hospital connection platform with role-based access for families and doctors.",sections:[
  ["The challenge","Families and doctors need connected ways to communicate and coordinate eldercare. The platform brings these interactions into a shared application."],
  ["My contribution","I built the full-stack platform using React, Node.js and Express.js, with PostgreSQL and Firebase in the stack."],
  ["What it includes","Role-based access for families and doctors, Google Gemini-powered features, and secure doctor-patient messaging."],
  ["The foundation","I designed backend APIs and the database schema to support scalable user interactions."]],note:"Project details from my original portfolio.",github:"https://github.com/Johnapatel"},
 {id:"gym",number:"06",title:"Gym — Fitness Tracker",category:"ANDROID DEVELOPMENT",date:"MOBILE FITNESS APPLICATION",theme:"gym",description:"Workout planning, progress tracking and fitness insights on Android.",stack:["Java","Android SDK"],metric:"Android",metricLabel:"native mobile application",Icon:Smartphone,question:"How can daily workouts become trackable progress?",introduction:"A mobile fitness tracker built with Java and Android SDK for planning workouts and tracking progress.",sections:[
  ["The idea","Bring workout planning and progress tracking together in a mobile application."],
  ["What I built","A native Android application with a BMI calculator, exercise search and filtering, and local data storage."],
  ["Tracking progress","Analytics help users review workout progress and exercise volume over time."],
  ["The stack","Java and Android SDK, with locally stored workout data."]],note:"Project details from my original portfolio.",github:"https://github.com/Johnapatel"}
];

export const email = "patelalok1947m@gmail.com";
