"use client";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {Compass,Mountain,Waves,ArrowUpRight,Clapperboard,FileVideo,MonitorPlay,Sparkles,Dumbbell} from "lucide-react";
import {skills,technologies,softSkills,timelines} from "@/lib/career-details";

export function HomeAbout(){return <><section className="home-about section-pad"><div className="reveal"><span className="eyebrow">A FEW MORE PIECES OF ME</span><h2>Grounded in logic.<br/><em>Driven by curiosity.</em></h2></div><div className="about-notes"><p className="reveal">I’m Alok Patel, a Computer Science graduate from Thapar Institute. I like understanding how things work—and finding my own way to make them better.</p><p className="reveal">My work moves between evaluating AI, building software and telling visual stories. Outside the screen, you’ll find me travelling, swimming or heading for a mountain trail.</p><div className="about-facts reveal"><span><b>2026</b>B.E. Computer Science</span><span><b>India</b>Open to AI/ML opportunities</span><span><b>Always</b>A work in progress</span></div><a className="outline-link reveal" href="https://linktr.ee/johnapatel" target="_blank" rel="noreferrer">All my connections <ArrowUpRight size={18}/></a></div></section><section className="home-beyond section-pad reveal"><span className="eyebrow">AWAY FROM THE KEYBOARD</span><h2>What I do <em>beyond coding.</em></h2><StoryJourney/></section></>}

const positions=[[17,49],[35,25],[70,37],[52,74],[17,21],[68,17],[83,60],[49,9],[18,78]];
export function CareerDetails({motion}:{motion:boolean}){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!motion)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{
  const mm=gsap.matchMedia();
  mm.add("(min-width: 701px)",()=>{const universe=root.current?.querySelector<HTMLElement>(".skills-universe");if(!universe)return;gsap.fromTo(".skill-orbit > span",{x:(i,el)=>universe.clientWidth*(.5-Number((el.parentElement as HTMLElement).dataset.x)/100),y:(i,el)=>universe.clientHeight*(.5-Number((el.parentElement as HTMLElement).dataset.y)/100),scale:.68,opacity:0},{x:0,y:0,scale:1,opacity:1,duration:1.25,stagger:.065,ease:"expo.out",scrollTrigger:{trigger:universe,start:"top 82%"}})});
  mm.add("(max-width: 700px)",()=>{gsap.from(".skill-orbit",{y:24,opacity:0,duration:.65,stagger:.055,ease:"power3.out",scrollTrigger:{trigger:".skills-universe",start:"top 85%"}})});
  gsap.utils.toArray<HTMLElement>(".timeline-group").forEach(group=>{gsap.from(group.querySelector(".timeline-progress"),{scaleY:0,ease:"none",scrollTrigger:{trigger:group,start:"top bottom",end:"center top",scrub:true}});});
  gsap.utils.toArray<HTMLElement>(".timeline-entry").forEach(entry=>{gsap.from(entry.querySelector(".timeline-copy"),{y:50,opacity:0,duration:.65,ease:"back.out(1.1)",scrollTrigger:{trigger:entry,start:"top 88%"}});gsap.from(entry.querySelector(".draw-circle"),{strokeDashoffset:126,duration:1,ease:"power2.inOut",scrollTrigger:{trigger:entry,start:"top 88%"}})});
 },root);return()=>ctx.revert()},[motion]);
 return <div ref={root} className="career-details section-pad"><section className="skills-section"><span className="eyebrow">THE KNOW-HOW / ALWAYS EVOLVING</span><h2>Skills<em>.</em></h2><div className="skills-universe"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><span className="skill-core">AI/ML</span>{skills.map((skill,i)=><span key={skill} className="skill-orbit" data-x={positions[i][0]} data-y={positions[i][1]} style={{left:`${positions[i][0]}%`,top:`${positions[i][1]}%`}}><span>{skill}</span></span>)}</div></section><div className="skill-columns">{[["Tools & Technologies",technologies],["Soft Skills",softSkills]].map(([title,items])=><section key={String(title)}><h3>{String(title)}</h3><div className="skill-pills">{(items as string[]).map((item,i)=><span key={item} style={{animationDelay:`${i*.12}s`}}>{item}</span>)}</div></section>)}</div>{timelines.map((group,index)=><section className="timeline-group" key={group.title}><div className="timeline-heading"><span className="eyebrow">0{index+1} / THE JOURNEY</span><h2>{group.title}<em>.</em></h2></div><div className="timeline-entries"><div className="timeline-progress"/>{group.entries.map(entry=><article className="timeline-entry" key={entry.title+entry.org}><svg className="timeline-dot" width="48" height="48" viewBox="0 0 50 50" aria-hidden="true"><circle cx="25" cy="25" r="20" fill="var(--background)" stroke="currentColor" opacity=".35"/><circle className="draw-circle" cx="25" cy="25" r="20" fill="none" stroke="currentColor" strokeWidth="3" strokeDasharray="126"/><circle className="pulse-dot" cx="25" cy="25" r="7" fill="currentColor"/></svg><div className="timeline-copy"><h3>{entry.title}{entry.org&&<> <em>@{entry.org}</em></>}</h3><p className="timeline-date">{entry.date}</p><ul>{entry.items.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div></section>)}</div>
}
export function StoryJourney(){return <div className="story-journey" aria-label="Gym, travelling, swimming and hiking inspire my stories">{[[Dumbbell,"Gym","Iron and sweat"],[Compass,"Travelling","A new perspective"],[Waves,"Swimming","Finding the flow"],[Mountain,"Hiking","Taking the long way"]].map(([Icon,title,caption],i)=>{const I=Icon as typeof Compass;return <div className="journey-stop" key={String(title)}><span className="journey-number">0{i+1} / FIELD NOTES</span><div className="journey-icon"><I strokeWidth={1}/><span/></div><h3>{String(title)}</h3><p>{String(caption)}</p></div>})}<div className="journey-trail" aria-hidden="true"/></div>}
export function VideoProcess(){const steps=[[Clapperboard,"Find the story","Define the feeling, the point of view and the arc before touching the timeline."],[FileVideo,"Build the rough cut","Select the strongest moments and arrange them until the pacing begins to breathe."],[MonitorPlay,"Shape it in software","Refine timing, sound, movement and transitions inside the editing workspace."],[Sparkles,"Finish the feeling","Polish colour, mix the audio, check every detail and prepare the final export."]];return <div className="edit-process" aria-label="My four-stage video editing process"><div className="process-line" aria-hidden="true"/>{steps.map(([Icon,title,copy],i)=>{const I=Icon as typeof Clapperboard;return <article className="process-step" key={String(title)}><span>0{i+1} / THE PROCESS</span><div><I strokeWidth={1.2}/><b>{String(title)}</b></div><p>{String(copy)}</p></article>})}</div>}
export function AuraTitle(){const words=["MAKE IT","FEEL","SOMETHING."];let offset=0;return <div className="aura-title"><div className="aura-halo" aria-hidden="true"/><div className="aura-shimmer" aria-hidden="true"/><span className="eyebrow">NOT JUST A CUT. A FEELING.</span><p aria-label="Make it feel something.">{words.map((word,wi)=><span key={word} className={wi===1?"aura-word aura-feel":"aura-word"} aria-hidden="true">{[...word].map((letter,i)=>{const delay=(offset+i)*.045;return <i key={`${word}-${i}`} style={{animationDelay:`${delay}s`}}>{letter===" "?"\u00a0":letter}</i>})}{(offset+=word.length+1)&&null}</span>)}</p><div className="aura-sparks" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:`${3+i*6}%`,animationDelay:`${i*.28}s`}}/>)}</div></div>}

export function SectionTransition({motion,section}:{motion:boolean;section:string}){const [phase,setPhase]=useState<"enter"|"idle"|"exit">(motion?"enter":"idle");useEffect(()=>{if(!motion){setPhase("idle");return}setPhase("enter");const enterTimer=window.setTimeout(()=>setPhase("idle"),900);const onClick=(event:MouseEvent)=>{const anchor=(event.target as HTMLElement).closest<HTMLAnchorElement>('a[href^="/"]');if(!anchor||anchor.target==="_blank"||anchor.hasAttribute("download")||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const url=new URL(anchor.href,window.location.href);if(url.pathname===window.location.pathname&&url.hash)return;event.preventDefault();setPhase("exit");window.setTimeout(()=>{window.location.href=url.href},720)};document.addEventListener("click",onClick,true);return()=>{window.clearTimeout(enterTimer);document.removeEventListener("click",onClick,true)}},[motion,section]);return <div className={`section-transition transition-${phase}`} aria-hidden="true"><div className="transition-rift"><span/><span/><span/></div><img src="/media/hero.webp" alt=""/><p>ARISE</p></div>}
